### ISSUE TITLE
several remarks

### ISSUE THREAD

**Issue by lyusupov** [lewisxhe/Acsip-S7XG_GPS-speedometer#1]
1) a typo in firmware folder name ?

    f-**ri**-mware:<br>
https://github.com/lewisxhe/Acsip-S7XG_GPS-speedometer/tree/master/frimware

2) confusing "T-Monitor" label

    there are several places in README where "T-Monitor" name is in use. What does it belong to ? Is it firmware name for **T-Motion** board ?

3) dfu.hex file is confusing as well.

    It supposed to be a firmware image of the sketch. However, in fact (according to 'hexview' and UNIX 'dmesg' output), it looks to me like an intermediate DFU bootloader for STM32:

```
[3936714.355437] usb 1-1.2.3: new full-speed USB device number 62 using dwc_otg
[3936714.491519] usb 1-1.2.3: New USB device found, idVendor=0483, idProduct=df11
[3936714.491537] usb 1-1.2.3: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[3936714.491548] usb 1-1.2.3: Product: STM32 DownLoad Firmware Update
[3936714.491559] usb 1-1.2.3: Manufacturer: STMicroelectronics
[3936714.491569] usb 1-1.2.3: SerialNumber: 044737423438
```

**Comment by lewisxhe** [comment]
😯 sorry, typo.
The firmware is indeed the DFU bootloader, not a compiled sketch. I was hasty, thank you for your reminder.

**Comment by lewisxhe** [comment]
If you do n’t remind me, I always thought it was called T-Monitor 😂

**Comment by lyusupov** [comment]
😄 
One more typo is :"RP", instead of PR (Pull Request)

And, are there any chances to get a binary of the firmware (.bin, . hex or .dfu - your choice) ? - I would try it out "as is".

**Comment by lewisxhe** [comment]
On Monday I will upload the compiled sketch. Thanks again for your reminder. Have a nice weekend.

**Comment by lyusupov** [comment]
And one more question is:
I am curious, what was the reason for you to provide an alternative DFU bootloader ?

As far as I remember, external DFU is necessary for "old" STM32 MCUs like STM32F103 and it's clones (GD32...). Factory bootloader in F103's ROM is very old and is unable to handle USB download method properly.

However, **L073 is relatively recent design**. It's built-in bootloader is rather new. It is capable to download firmware from either of UART1 (PA9/PA10), UART2 (PA2/PA3) and USB (PA11/PA12). It senses which one is active automatically. 
At it works quite reliable to me.

**Comment by lewisxhe** [comment]
is it ? I always thought it was not a built-in DFU bootloader like the GD32, and I will try what you said again.

**Comment by lyusupov** [comment]
[AN2606](https://www.st.com/content/ccc/resource/technical/document/application_note/b9/9b/16/3a/12/1e/40/0c/CD00167594.pdf/files/CD00167594.pdf/jcr:content/translations/en.CD00167594.pdf) gives every detail about what revision of the bootloader is built-in and what f/w download options are available for every of STM32 products.

**Comment by lewisxhe** [comment]
Thanks, I have uploaded the sketch firmware and can use the `dfu-util.exe -a 0  -s 0x08000000 -R -D .\firmware.bin` command for programming.

**Comment by lyusupov** [comment]
Yes, I can confirm that it works nicely to me:

![P91230-102356-001](https://user-images.githubusercontent.com/5849637/71572446-3b157100-2af0-11ea-9afd-bf831cdd58bb.jpg)

Thank you!
